export const rulesCategoryJson = [
  {
    id: 1,
    name: "All",
    variables: [],
    rules: [
      {
        all: [{ value: "Todos", categoryId: [2, 173, 159] }],
      },
    ],
  },
  {
    id: 2,
    name: "Gender + type",
    variables: ["gender", "type"],
    rules: [
      {
        gender: [
          { value: "Feminino", categoryId: 136 },
          { value: "Unissex", categoryId: 341 },
        ],
        type: [
          { value: "Babuch", categoryId: 194 },
          { value: "Bota", categoryId: 266 },
          { value: "Chinelo de Dedo", categoryId: 137 },
          { value: "Chinelo de Gáspea/Slide", categoryId: 138 },
          { value: "Rasteirinhas", categoryId: 147 },
          { value: "Sandália", categoryId: 139 },
          { value: "Sapatilha", categoryId: 193 },
          { value: "Tamanco", categoryId: 140 },
          { value: "Tênis", categoryId: 192 },
          { value: "BOLSA", categoryId: 293 },
        ],
      },
      {
        gender: [
          { value: "Masculino", categoryId: 141 },
          { value: "Unissex", categoryId: 341 },
        ],
        type: [
          { value: "Babuch", categoryId: 195 },
          { value: "Bota", categoryId: 274 },
          { value: "Chinelo de Dedo", categoryId: 157 },
          { value: "Chinelo de Gáspea/Slide", categoryId: 152 },
          { value: "Rasteirinhas", categoryId: 0 },
          { value: "Sandália", categoryId: 153 },
          { value: "Sapatilha", categoryId: 0 },
          { value: "Tamanco", categoryId: 0 },
          { value: "Tênis", categoryId: 0 },
          { value: "BOLSA", categoryId: 0 },
        ],
      },
      {
        gender: [{ value: "Infantil", categoryId: 142 }],
        type: [
          { value: "Babuch", categoryId: 151 },
          { value: "Bota", categoryId: 146 },
          { value: "Chinelo de Dedo", categoryId: 143 },
          { value: "Chinelo de Gáspea/Slide", categoryId: 144 },
          { value: "Rasteirinhas", categoryId: 148 },
          { value: "Sandália", categoryId: 145 },
          { value: "Sapatilha", categoryId: 154 },
          { value: "Tamanco", categoryId: 0 },
          { value: "Tênis", categoryId: 0 },
          { value: "BOLSA", categoryId: 0 },
        ],
      },
      {
        gender: [{ value: "Baby", categoryId: 179 }],
        type: [
          { value: "Babuch", categoryId: 188 },
          { value: "Bota", categoryId: 189 },
          { value: "Chinelo de Dedo", categoryId: 181 },
          { value: "Chinelo de Gáspea/Slide", categoryId: 191 },
          { value: "Rasteirinhas", categoryId: 148 },
          { value: "Sandália", categoryId: 180 },
          { value: "Sapatilha", categoryId: 252 },
          { value: "Tamanco", categoryId: 0 },
          { value: "Tênis", categoryId: 190 },
          { value: "BOLSA", categoryId: 0 },
        ],
      },
    ],
  },
  {
    id: 3,
    name: "Brand",
    variables: ["brand", "gender"],
    rules: [
      {
        gender: [
          { value: "Masculino", categoryId: 0 },
          { value: "Feminino", categoryId: 0 },
          { value: "Unissex", categoryId: 0 },
        ],
        brand: [
          { value: "Cartago", categoryId: 164 },
          { value: "Ipanema", categoryId: 167 },
          { value: "Rider", categoryId: 169 },
          { value: "Grendha", categoryId: 165 },
          { value: "Azaleia", categoryId: 163 },
          { value: "Zaxy", categoryId: 170 },
          { value: "Grendene Kids", categoryId: 166 },
          { value: "Mormaii", categoryId: 168 },
          { value: "Teste", categoryId: 0 },
          { value: "PEGA FORTE", categoryId: 342 },
        ],
      },
      {
        gender: [
          { value: "Infantil", categoryId: 0 },
          { value: "Baby", categoryId: 0 },
        ],
        brand: [
          { value: "Cartago Kids", categoryId: 220 },
          { value: "Ipanema Kids", categoryId: 229 },
          { value: "Rider Kids", categoryId: 245 },
          { value: "Grendha Kids", categoryId: 225 },
          { value: "Azaleia", categoryId: 0 },
          { value: "Zaxynina", categoryId: 251 },
          { value: "Grendene Kids", categoryId: 166 },
          { value: "Mormaii", categoryId: 0 },
          { value: "Teste", categoryId: 0 },
          { value: "PEGA FORTE", categoryId: 0 },
        ],
      },
    ],
  },
  {
    id: 4,
    name: "Others",
    variables: ["name"],
    rules: [
      {
        name: [
          { value: ["A Casa Mágica de Gabby"], categoryId: [278] },
          { value: ["Any Malu"], categoryId: [213] },
          { value: ["Authentic Games"], categoryId: [214] },
          {
            value: ["Avengers", "Vingadores"],
            categoryId: [215, 237],
          },
          { value: ["Baby Shark"], categoryId: [216] },
          { value: ["Batman"], categoryId: [217, 232] },
          { value: ["Barbie"], categoryId: [218] },
          { value: ["BT 21"], categoryId: [219] },
          { value: ["Cavalinhos do Fantástico"], categoryId: [312] },
          { value: ["Disney"], categoryId: [222] },
          { value: ["Frozen"], categoryId: [223, 222] },
          { value: ["Galinha Pintadinha"], categoryId: [224] },
          { value: ["Harry Potter"], categoryId: [226] },
          { value: ["Homem Aranha"], categoryId: [227, 215, 237] },
          { value: ["Hot Wheels"], categoryId: [228] },
          {
            value: ["Jurassic Park", "Jurassic World"],
            categoryId: [230],
          },
          { value: ["Lady Bug"], categoryId: [231] },
          { value: ["Lilo & Stitch"], categoryId: [304, 222, 272] },
          { value: ["Liga da Justiça"], categoryId: [232] },
          { value: ["LOL Surprise"], categoryId: [233] },
          { value: ["Luluca"], categoryId: [234] },
          { value: ["Looney Tunes"], categoryId: [235] },
          { value: ["Manual do Mundo"], categoryId: [236] },
          { value: ["Marvel"], categoryId: [237] },
          { value: ["Max Steel"], categoryId: [238, 272] },
          { value: ["Meu sol"], categoryId: [279] },
          {
            value: ["Minnie e Mickey", "Mickey", "Minnie"],
            categoryId: [239, 222, 272],
          },
          { value: ["Minions"], categoryId: [240] },
          { value: ["Moranguinho"], categoryId: [241] },
          { value: ["Mundo Bita"], categoryId: [268] },
          { value: ["Naruto"], categoryId: [242] },
          { value: ["NBA"], categoryId: [368] },
          { value: ["Now United"], categoryId: [243] },
          { value: ["One piece"], categoryId: [360] },
          { value: ["Patrulha Canina"], categoryId: [244, 272] },
          { value: ["Sonic"], categoryId: [246] },
          { value: ["Super Mario"], categoryId: [247] },
          { value: ["Totoykids"], categoryId: [248] },
          {
            value: ["Turma do Chaves e Chapolin", "Chapolin", "Chaves"],
            categoryId: [249],
          },
          {
            value: ["Turma da Mônica", "Chico Bento", "Mônica"],
            categoryId: [250, 272],
          },
          { value: ["Ursinhos Carinhosos"], categoryId: [265] },
          { value: ["Wandinha"], categoryId: [267] },
        ],
      },
    ],
  },
  {
    id: 5,
    name: "Promotion",
    variables: ["promotion", "gender"],
    rules: [
      {
        promotion: [{ value: "PROMO", categoryId: 175 }],
        gender: [
          { value: "Masculino", categoryId: 187 },
          { value: "Feminino", categoryId: 185 },
          { value: "Infantil", categoryId: 186 },
          { value: "Baby", categoryId: 186 },
        ],
      },
    ],
  },
  {
    id: 6,
    name: "Release",
    variables: ["gender"],
    rules: [
      {
        gender: [
          { value: "Masculino", categoryId: 0 },
          { value: "Feminino", categoryId: 0 },
          { value: "Infantil", categoryId: 0 },
          { value: "Baby", categoryId: 0 },
        ],
      },
    ],
  },
];
